apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  containers:
  - env:
    - name: DATABASE_URL
      value: postgres://postgres:password@postgres:5432/cas_shipit_development
    - name: RAILS_ENV
      value: development
    - name: REDIS_URL
      value: redis://redis:6379
    - name: RAILS_MASTER_KEY
      valueFrom:
        secretKeyRef:
          key: master_key
          name: {{ .Release.Name }}-auth
    image: "{{ .Values.repoUrl }}:{{ .Values.image_tag }}"
    imagePullPolicy: Always
    name: app
    ports:
    - containerPort: 3000
    resources: {}
  restartPolicy: OnFailure
status: {}
