apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  containers:
  - args:
    - bundle
    - exec
    - sidekiq
    - -C
    - config/sidekiq.yml
    env:
    - name: DATABASE_URL
      value: postgres://postgres:password@postgres:5432
    - name: REDIS_URL
      value: redis://redis:6379
    - name: RAILS_MASTER_KEY
      valueFrom:
        secretKeyRef:
          key: master_key
          name: {{ .Release.Name }}-auth
    image: "491327797652.dkr.ecr.ca-central-1.amazonaws.com/shipit-images:{{ .Values.image_tag }}"
    imagePullPolicy: Always
    name: worker
    resources: {}
  restartPolicy: OnFailure
status: {}
