version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  tools:
      docker:  
        - image: cimg/base:2020.01
      steps:
        - checkout
        - run:
            name: Install python dependencies
            command: |
              sudo apt-get update
              sudo apt-get -y install --no-install-recommends make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
        - restore_cache:
            name: Restore asdf Tools Cache
            keys:
              - tool-versions-{{ checksum ".tool-versions" }}-v2
        - run:
            name: Install asdf
            command: |
              [ ! -f ".tool-versions" ] && echo "file .tool-versions was not found" && exit 1
              [ -d ~/.asdf ] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.4
              echo 'source ~/.asdf/asdf.sh' >> $BASH_ENV
        - run:
            name: Install asdf tools
            command: |
              asdf install
              asdf reshim
              pip install pre-commit
        - save_cache:
            name: Save asdf Tools Cache
            key: tool-versions-{{ checksum ".tool-versions" }}-v2
            paths:
              - ~/.asdf
        - persist_to_workspace:
            root: ~/
            paths:
              - .asdf
              - .bashrc
  lint:
    docker:  
        - image: cimg/base:2020.01
    steps:
        - checkout
        - attach_workspace:
            at: ~/
        - run:
            name: install dependencies
            command: |
              sudo apt-get update
              sudo apt-get -y install zlib1g-dev libpq-dev
        - restore_cache:
            name: Restore gems
            keys:
              - gem-cache-{{ checksum "Gemfile.lock" }}
        - run:
            name: pre-commit
            command: |
              source ~/.asdf/asdf.sh 
              asdf global postgres 11.4
              asdf reshim 
              bundle install
              pre-commit run --all-files
        - save_cache:
            name: Save asdf Tools Cache
            key: gem-cache-{{ checksum "Gemfile.lock" }}
            paths:
              - vendor/bundle
  push-heroku:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Publish to Heroku Server
          command: |
            rm -rf .git
            rm .gitignore
            rm config/credentials.yml.enc
            mv config/credentials-prod.yml.enc config/credentials.yml.enc
            git init
            git config user.email "$USER_EMAIL"
            git config user.name "$USER_NAME"
            git add .
            git commit -m "CircleCI Pipeline"
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version: 2
  pipeline:
    jobs:
      - tools
      - lint:
          requires:
            - tools
      - push-heroku:
          filters:
            branches:
              only:
                - develop
