version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  push-heroku:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Publish to Heroku Server
          command: |
            rm -rf .git
            rm config/credentials.yml.enc
            mv config/credentials-prod.yml.enc config/credentials.yml.enc
            git init
            git config user.email "$USER_EMAIL"
            git config user.name "$USER_NAME"
            git add .
            git commit -m "CircleCI Pipeline"
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version: 2
  pipeline:
    jobs:
      - push-heroku:
          filters:
            branches:
              only:
                - develop
